config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  # root home page
  root 'static_pages#home'

  # user login/logout
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  # users
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  # roasters
  resources :roasters

  # coffees
  resources :coffees

  # static page routing
  get '/help', to: 'static_pages#help'
end

app/models/coffee.rb
class Coffee < ApplicationRecord
  belongs_to :roaster
  validates :name, presence: true
  validates :roaster, presence: true
end

app/controllers/coffees_controller.rb
class CoffeesController < ApplicationController
  before_action :logged_in_user, only: [:new, :create]

  def index
    @coffees = Coffee.all
  end

  def show
    @coffee = Coffee.find(params[:id])
  end

  def new
    @coffee = Coffee.new
  end

  def create
    @coffee = Coffee.new(coffee_params)
    if @coffee.save
      flash[:success] = 'Coffee successfully added'
      redirect_to coffee_path(@coffee)
    else
      render 'new'
    end
  end

  private

  def coffee_params
    params.require(:coffee).permit(:name)
  end
end

app/helpers/coffees_helper.rb
module CoffeesHelper
end

app/views/coffees/_form.html.erb
<%= form_for(@coffee) do |f| %>
  <%= render 'shared/coffee_error_messages', object: @coffee %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/coffees/index.html.erb
<% provide(:title, 'Coffees') %>
<%= link_to 'Add new coffee', new_coffee_path, class: 'btn btn-lg btn-primary' %>
<h1>
  <% @coffees.each do |coffee| %>
    <%= coffee.name %>
  <% end %>
</h1>

app/views/coffees/new.html.erb
<% provide(:title, 'Add coffee') %>
<% provide(:button_text, 'Add new coffee') %>
<h1>Add coffee</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/coffees/show.html.erb
<% provide(:title, @coffee.name) %>
<h1>
  <%= @coffee.name %>
</h1>