config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  # root home page
  root 'static_pages#home'

  # user login/logout
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  # users
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  # roasters
  resources :roasters

  # coffees
  resources :coffees

  # static page routing
  get '/help', to: 'static_pages#help'
end

app/models/roaster.rb
class Roaster < ApplicationRecord
  has_many :reviews, through: :coffees
  has_many :coffees
  validates :name, presence: true
end

app/controllers/roasters_controller.rb
class RoastersController < ApplicationController
  before_action :logged_in_user, only: [:new, :create]

  def index
    @roasters = Roaster.all
  end

  def show
    @roaster = Roaster.find(params[:id])
  end

  def new
    @roaster = Roaster.new
  end

  def create
    @roaster = Roaster.new(roaster_params)
    if @roaster.save
      flash[:success] = 'Roaster successfully added'
      redirect_to roaster_path(@roaster)
    else
      render 'new'
    end
  end

  private

  def roaster_params
    params.require(:roaster).permit(:name)
  end
end

app/helpers/roasters_helper.rb
module RoastersHelper
end

app/views/roasters/_form.html.erb
<%= form_for(@roaster) do |f| %>
  <%= render 'shared/roaster_error_messages', object: @roaster %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/roasters/index.html.erb
<% provide(:title, 'Roasters') %>
<%= link_to 'Add new roaster', new_roaster_path, class: 'btn btn-lg btn-primary' %>
<h1>
  <% @roasters.each do |roaster| %>
    <%= roaster.name %>
  <% end %>
</h1>

app/views/roasters/new.html.erb
<% provide(:title, 'Add roaster') %>
<% provide(:button_text, 'Add new roaster') %>
<h1>Add roaster</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/roasters/show.html.erb
<% provide(:title, @roaster.name) %>
<h1>
  <%= @roaster.name %>
</h1>